export enum PROPERTY_TYPES {
  HOUSE = 'HOUSE',
  LAND = 'LAND',
  APARTMENT = 'APARTMENT',
  BUSINESS_AND_COMMERCIAL = 'BUSINESS_AND_COMMERCIAL',
  FLAT = 'FLAT',
  ROOM = 'ROOM',
  HOUSING = 'HOUSING',
}
